// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Outlaws.API.Data;

namespace Outlaws.API.Migrations
{
    [DbContext(typeof(OutlawContext))]
    [Migration("20210428081024_Seeding")]
    partial class Seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("ProjectBackendDevelopment.Models.DeathCause", b =>
                {
                    b.Property<Guid>("DeathCauseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeathUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeathCauseId");

                    b.ToTable("DeathCauses");

                    b.HasData(
                        new
                        {
                            DeathCauseId = new Guid("2db1b768-d37e-4c12-bf15-1006df06746f"),
                            DeathUri = "http://dbpedia.org/resource/Gunshot_wounds",
                            Description = "Gunshot wound"
                        });
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.Gang", b =>
                {
                    b.Property<Guid>("GangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GangName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GangUri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GangId");

                    b.ToTable("Gangs");

                    b.HasData(
                        new
                        {
                            GangId = new Guid("911b4ff0-bb44-49dd-b3ad-dd993cf04641"),
                            GangName = "Butch Cassidy's Wild Bunch",
                            GangUri = "http://dbpedia.org/resource/Butch_Cassidy's_Wild_Bunch"
                        },
                        new
                        {
                            GangId = new Guid("fd4eb443-dacb-4c08-9731-b7a10d5d4d35"),
                            GangName = "Butch Cassidy's Wild Bunch",
                            GangUri = "https://dbpedia.org/resource/James-Younger_Gang"
                        });
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.GangOutlaw", b =>
                {
                    b.Property<Guid>("GangId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutlawId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GangId", "OutlawId");

                    b.HasIndex("OutlawId");

                    b.ToTable("GangOutlaw");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.Outlaw", b =>
                {
                    b.Property<Guid>("OutlawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DeathCauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeathDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutlawUri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutlawId");

                    b.HasIndex("DeathCauseId");

                    b.ToTable("Outlaws");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.GangOutlaw", b =>
                {
                    b.HasOne("ProjectBackendDevelopment.Models.Gang", "Gang")
                        .WithMany("GangOutlaws")
                        .HasForeignKey("GangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectBackendDevelopment.Models.Outlaw", "Outlaw")
                        .WithMany("GangOutlaws")
                        .HasForeignKey("OutlawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gang");

                    b.Navigation("Outlaw");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.Outlaw", b =>
                {
                    b.HasOne("ProjectBackendDevelopment.Models.DeathCause", "Deathcauses")
                        .WithMany("Outlaws")
                        .HasForeignKey("DeathCauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deathcauses");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.DeathCause", b =>
                {
                    b.Navigation("Outlaws");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.Gang", b =>
                {
                    b.Navigation("GangOutlaws");
                });

            modelBuilder.Entity("ProjectBackendDevelopment.Models.Outlaw", b =>
                {
                    b.Navigation("GangOutlaws");
                });
#pragma warning restore 612, 618
        }
    }
}
